org: rataque
app: serverless-bootcamp
service: notification-service

plugins:
  - serverless-offline

package:
  individually: true
  patterns:
    - node_modules/**

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 256
  timeout: 10
  stage: ${opt:stage, 'dev'}
  region: us-east-2

#functions:

custom:
  bundle:
    linting: false
    packager: 'yarn'
  babelPresets:
    - latest
